[package]
name = "sebi"
version = "0.1.0"
edition = "2021"

[lib]
name = "sebi"
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.30.1"
anchor-spl  = "0.30.1"
solana-program = "1.16.17"
